=== shawonalpha/Web-Development/Anime/Exp/AnimeTable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="AnimeTable" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="AnimeTable">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="WatchOrder " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="WatchOrder" index-key="WatchOrder " primary="no" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAABQ/BtSpwolT4jKPqj/rCZxAAAAAG0vtyjvluVAYMEWASU/My9BAG4A
aQBtAGUAVABhAGIAbABlAAAAAAAAAN+K7+yk86FDvmRaFMDp0S4HAAAAUPwbUqcK
JU+Iyj6o/6wmcVcAYQB0AGMAaABPAHIAZABlAHIAAAAAAAAAbikBG92960O8a/pe
vtjAEgcAAABQ/BtSpwolT4jKPqj/rCZxUgBhAHQAaQBuAGcAcwAAAAAAAAADjEEy
pCCSRYgoNXE8r5+yBwAAAFD8G1KnCiVPiMo+qP+sJnFDAG8AbQBwAGwAZQB0AGUA
ZAAAAAAAAAApj7tnWA+pT7HoMbkrGlN6BwAAAFD8G1KnCiVPiMo+qP+sJnFBAG4A
aQBtAGUATgBhAG0AZQAAAAAAAABEEp701EUXTpocdEYtXAC1BwAAAFD8G1KnCiVP
iMo+qP+sJnFHAGUAbgByAGUAAAAAAAAA1vDZ1HpnYkKlqxbniDqtAgcAAABQ/BtS
pwolT4jKPqj/rCZxVABvAHQAYQBsACAARQBwAGkAcwBvAGQAZQBzAAAAAAAAAE2r
Jf77DhdIpeq9VWNwN0kHAAAAUPwbUqcKJU+Iyj6o/6wmcUQAcgBvAHAAcABlAGQA
AAAAAAAAj/9E0O8Ud0GFdvUiTDzxEQcAAABQ/BtSpwolT4jKPqj/rCZxRQBwAGkA
cwBvAGQAZQAgAFcAYQB0AGMAaABlAGQAAAAAAAAAbybpATE/AUKAAqTLZJi0tAcA
AABQ/BtSpwolT4jKPqj/rCZxUgBlAG0AYQByAGsAcwAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAADAAAAAQAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="UPwbUqcKJU+Iyj6o/6wmcQ==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="FrozenColumns" type="3" value="1"/>
<od:tableProperty name="OrderBy" type="12" value="[AnimeTable].[WatchOrder], [AnimeTable].[Ratings] DESC, [AnimeTable].[Completed], [AnimeTable].[AnimeName]"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="WatchOrder" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="34rv7KTzoUO+ZFoUwOnRLg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="AnimeName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="5250"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="KY+7Z1gPqU+x6DG5KxpTeg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Ratings" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="bikBG92960O8a/pevtjAEg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Genre" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="RBKe9NRFF06aHHRGLVwAtQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Total_x0020_Episodes" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="1vDZ1HpnYkKlqxbniDqtAg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Completed" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1440"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="A4xBMqQgkkWIKDVxPK+fsg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Dropped" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="Tasl/vsOF0il6r1VY3A3SQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Episode_x0020_Watched" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1845"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="j/9E0O8Ud0GFdvUiTDzxEQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Remarks" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4290"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="bybpATE/AUKAAqTLZJi0tA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== shawonalpha/Web-Development/Anime/Exp/AnimeTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="AnimeTable.xsd" generated="2021-01-26T23:06:44">
<AnimeTable>
<WatchOrder>262</WatchOrder>
<AnimeName>Cowboy Bebop</AnimeName>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>263</WatchOrder>
<AnimeName>Crono Crusasde</AnimeName>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>264</WatchOrder>
<AnimeName>Jujutsu Kaisen</AnimeName>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>265</WatchOrder>
<AnimeName>Standing on 1M lives</AnimeName>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>266</WatchOrder>
<AnimeName>King&apos;s Raid</AnimeName>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>267</WatchOrder>
<AnimeName>Shinkekai Yori</AnimeName>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>268</WatchOrder>
<AnimeName>Shimoneta</AnimeName>
<Ratings>7.2</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
<Episode_x0020_Watched>12</Episode_x0020_Watched>
</AnimeTable>
<AnimeTable>
<WatchOrder>269</WatchOrder>
<AnimeName>Our Last Crusade</AnimeName>
<Total_x0020_Episodes>12</Total_x0020_Episodes>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>270</WatchOrder>
<AnimeName>The Money &amp; Soul of Prossibility</AnimeName>
<Ratings>7.12</Ratings>
<Total_x0020_Episodes>11</Total_x0020_Episodes>
<Completed>1</Completed>
<Dropped>0</Dropped>
<Episode_x0020_Watched>13</Episode_x0020_Watched>
</AnimeTable>
<AnimeTable>
<WatchOrder>271</WatchOrder>
<AnimeName>Kiznaiver</AnimeName>
<Completed>1</Completed>
<Dropped>0</Dropped>
<Episode_x0020_Watched>13</Episode_x0020_Watched>
</AnimeTable>
<AnimeTable>
<WatchOrder>272</WatchOrder>
<AnimeName>Tales of Zesteria the X</AnimeName>
<Completed>0</Completed>
<Dropped>0</Dropped>
<Remarks>opening../</Remarks>
</AnimeTable>
<AnimeTable>
<WatchOrder>273</WatchOrder>
<AnimeName>Aldnoah Zero</AnimeName>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>274</WatchOrder>
<AnimeName>Blood Lad</AnimeName>
<Ratings>7.1</Ratings>
<Total_x0020_Episodes>10</Total_x0020_Episodes>
<Completed>1</Completed>
<Dropped>0</Dropped>
<Remarks>donâ€™t be fooled by crappy cover</Remarks>
</AnimeTable>
<AnimeTable>
<WatchOrder>275</WatchOrder>
<AnimeName>Akudama Drive</AnimeName>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>276</WatchOrder>
<AnimeName>Dorohedoro</AnimeName>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>277</WatchOrder>
<AnimeName>Tonikawa Kawai</AnimeName>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>278</WatchOrder>
<AnimeName>Talentless Nana</AnimeName>
<Ratings>8.25</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
<Episode_x0020_Watched>13</Episode_x0020_Watched>
</AnimeTable>
<AnimeTable>
<WatchOrder>279</WatchOrder>
<AnimeName>Heaven Official&apos;s Blessing</AnimeName>
<Ratings>7.85</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
<Episode_x0020_Watched>11</Episode_x0020_Watched>
</AnimeTable>
<AnimeTable>
<WatchOrder>280</WatchOrder>
<AnimeName>Grand Blue</AnimeName>
<Ratings>8.02</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>281</WatchOrder>
<AnimeName>Welcome To Demon School</AnimeName>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>282</WatchOrder>
<AnimeName>Golden Boy</AnimeName>
<Ratings>7.56</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
<Episode_x0020_Watched>5</Episode_x0020_Watched>
</AnimeTable>
<AnimeTable>
<WatchOrder>283</WatchOrder>
<AnimeName>Nagi No Asu Kara</AnimeName>
<Ratings>8.65</Ratings>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>284</WatchOrder>
<AnimeName>Drifters</AnimeName>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>285</WatchOrder>
<AnimeName>By the Grace of Gods</AnimeName>
<Ratings>7.65</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>286</WatchOrder>
<AnimeName>Berserk</AnimeName>
<Ratings>8.65</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>287</WatchOrder>
<AnimeName>Moriarty The Patriot</AnimeName>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>288</WatchOrder>
<AnimeName>One Outs</AnimeName>
<Ratings>8.65</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>289</WatchOrder>
<AnimeName>Jossless Reincarnation</AnimeName>
<Ratings>8</Ratings>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>290</WatchOrder>
<AnimeName>Welcome To N.H.K</AnimeName>
<Ratings>7.65</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
<Episode_x0020_Watched>25</Episode_x0020_Watched>
</AnimeTable>
<AnimeTable>
<WatchOrder>291</WatchOrder>
<AnimeName>Dusk Maiden of Anmesia</AnimeName>
<Ratings>8.35</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
<Episode_x0020_Watched>13</Episode_x0020_Watched>
</AnimeTable>
<AnimeTable>
<WatchOrder>292</WatchOrder>
<AnimeName>Trigun</AnimeName>
<Ratings>8.65</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
<Episode_x0020_Watched>26</Episode_x0020_Watched>
</AnimeTable>
<AnimeTable>
<WatchOrder>293</WatchOrder>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>294</WatchOrder>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>295</WatchOrder>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>296</WatchOrder>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>297</WatchOrder>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>298</WatchOrder>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>299</WatchOrder>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>300</WatchOrder>
<Completed>0</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>2</WatchOrder>
<AnimeName>DB Series</AnimeName>
<Ratings>9.6</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>3</WatchOrder>
<AnimeName>Death Note</AnimeName>
<Ratings>9.25</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>4</WatchOrder>
<AnimeName>Code Geass</AnimeName>
<Ratings>9.5</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>5</WatchOrder>
<AnimeName>Hunter X Hunter</AnimeName>
<Ratings>8.39</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>6</WatchOrder>
<AnimeName>HighSchool DxD</AnimeName>
<Ratings>9.29</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>7</WatchOrder>
<AnimeName>Charlotee</AnimeName>
<Ratings>7.53</Ratings>
<Total_x0020_Episodes>12</Total_x0020_Episodes>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>8</WatchOrder>
<AnimeName>Akame Ga Kill</AnimeName>
<Ratings>8.75</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>9</WatchOrder>
<AnimeName>Prison School</AnimeName>
<Ratings>3.1</Ratings>
<Completed>1</Completed>
<Dropped>1</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>10</WatchOrder>
<AnimeName>Familer of Zero</AnimeName>
<Ratings>6.15</Ratings>
<Completed>0</Completed>
<Dropped>1</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>11</WatchOrder>
<AnimeName>Monster Musume</AnimeName>
<Ratings>5.6</Ratings>
<Total_x0020_Episodes>12</Total_x0020_Episodes>
<Completed>0</Completed>
<Dropped>1</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>12</WatchOrder>
<AnimeName>Masau Gakun HXH</AnimeName>
<Ratings>7.15</Ratings>
<Total_x0020_Episodes>12</Total_x0020_Episodes>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>13</WatchOrder>
<AnimeName>SAO</AnimeName>
<Ratings>8.95</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>14</WatchOrder>
<AnimeName>Hajiimeto no Gal</AnimeName>
<Ratings>6.2</Ratings>
<Total_x0020_Episodes>12</Total_x0020_Episodes>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>15</WatchOrder>
<AnimeName>Shimmai Maou no Testament</AnimeName>
<Ratings>8.50</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>16</WatchOrder>
<AnimeName>Trinity Seven</AnimeName>
<Ratings>7.77</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>17</WatchOrder>
<AnimeName>Highschool of the dead</AnimeName>
<Ratings>6.9</Ratings>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>18</WatchOrder>
<AnimeName>KissXsis</AnimeName>
<Ratings>7.7</Ratings>
<Total_x0020_Episodes>12</Total_x0020_Episodes>
<Completed>1</Completed>
<Dropped>0</Dropped>
</AnimeTable>
<AnimeTable>
<WatchOrder>19</WatchOrder>
<AnimeName>Freezing</AnimeName>
<Ratings>6.21</Ratings>
<Total_x0020_Episodes>12</Total_x0020_Episodes>
<Completed>1</Completed>
